MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet'   #vgg   #'basic'
        PRETRAINED: False
        OUT_CHANNELS: [1024, 2048, 1024, 1024, 512, 512]  #[512,1024,2048,512, 256, 128]    
        INPUT_CHANNELS: 3
        DEPTH: 50
        DROP_BLOCK: False
        AFTER_TRAINED: True
        AFTER_TRAINED_File: 'outputs/Res34_20_Apr/Res50_TA_no_Maxpool/model_final.pth'
    PRIORS:
        FEATURE_MAPS: [[30,40], [15,20], [8,10], [4,5], [2,3], [1,2]]
        STRIDES: [[8,8], [16,16], [30,32], [60,64], [120,106], [240,160]]
        MIN_SIZES: [[17,23], [36,48], [80,106], [123,164], [166,221], [208,278]]
        MAX_SIZES: [[36,48], [80,106], [123,164], [166,221], [208,278], [252,336]]
        ASPECT_RATIOS: [[2], [2,3], [2, 3], [2, 3], [2], [2]]
        BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
INPUT:
    IMAGE_SIZE: [240,320]  #[H,W]
        
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
DATA_LOADER:
    DATA_AUGMENTATION: 'paper'
    AUGMENTATION_WEATHER: True
#     AUGMENTATION_SPATIAL_LEVEL: True
SOLVER:
    CHOICE: 'SGD'
    MAX_ITER:  30000
    LR_STEPS: [20000, 25000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 2e-3
    WARMUP_ITERS: 1000
OUTPUT_DIR: 'outputs/Res34_21_Apr/TDT_Res50_no_Maxpool_lufficc'
DATASET_DIR: "datasets"