MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet'   #vgg   #'basic'
        PRETRAINED: True
        OUT_CHANNELS: [512,1024,2048,512, 256, 128]     #[128, 256, 512, 512, 256, 128]
        INPUT_CHANNELS: 3
        DEPTH: 50
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    CHOICE: 'SGD'
    MAX_ITER:  65000
    LR_STEPS: [30000, 60000]
    GAMMA: 0.1
    BATCH_SIZE: 32
    LR: 1.e-2
OUTPUT_DIR: 'outputs/res50_new_waymo_sgd_1e_f2'  
DATASET_DIR: "datasets"