MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet'   
        PRETRAINED: True
        OUT_CHANNELS: [512, 512, 256, 256, 128, 128]      
        INPUT_CHANNELS: 3
        DEPTH: 34
        DROP_BLOCK: False
    PRIORS:
        FEATURE_MAPS: [[30,40], [15,20], [8,10], [4,5], [2,3], [1,2]]
        STRIDES: [[8,8], [16,16], [30,32], [60,64], [120,106], [240,160]]
        MIN_SIZES: [[17,23], [36,48], [80,106], [123,164], [166,221], [208,278]]
        MAX_SIZES: [[36,48], [80,106], [123,164], [166,221], [208,278], [252,336]]
        ASPECT_RATIOS: [[2], [2,3], [2, 3], [2, 3], [2], [2]]
        BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
INPUT:
    IMAGE_SIZE: [240,320]  #[H,W]
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
DATA_LOADER:
    NUM_WORKERS: 8
SOLVER:
    CHOICE: 'SGD'
    MAX_ITER:  45000
    LR_STEPS: [35000, 40000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-2
    WARMUP_ITERS: 1500
OUTPUT_DIR: 'outputs/waymo_final_model'  
DATASET_DIR: "datasets"